applications:
- name: producer
  path: target/spring-boot-rabbit-messaging-0.1.0.jar
  disk_quota: 1G
  instances: 1
  memory: 1G
  random-route: true
  services:
  - rabbit1
  env:
    CONSUMER: false
    PRODUCER: true
